version: "3.4"
services:
  db:
    image: postgres:12-alpine
    container_name: todo_actix_db
    restart: always
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./db/dev/postgres:/var/lib/postgresql/data
    ports:
      - 5434:5432
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'

  todo-actix:
    build: .
    depends_on:
      - db
    environment:
      - SERVER.HOST=0.0.0.0
      - SERVER.PORT=8080
      - DATABASE.HOST=db
      - DATABASE.PORT=5432
      - DATABASE.DBNAME=todo
      - DATABASE.USER=admin
      - DATABASE.PASSWORD=admin
      - DATABASE.POOL.MAX_SIZE=15
    deploy:
      resources:
        limits:
          memory: '1G'
          cpus: '2'

    ports:
      - 8080:8080
